#!/bin/sh
# Push to luevano.xyz

# This pushes everything! (except for blog and art, since it needs a bit more management)
echo "rsync: pushing (U) local (lz) to webserver (lzserver). (luevano.xyz)"
rsync -rtuvPL --delete-after --exclude-from=$HOME/luevano.xyz/.rsyncignore $HOME/luevano.xyz/ luevanor:/var/www/

# This pushes the blog.
echo "rsync: pushing (U) local (lz) to webserver (lzserver). (blog.luevano.xyz)"
rsync -rtuvPL --delete-after $HOME/luevano.xyz/blog/dst/ luevanor:/var/www/blog/

# This pushes the art.
echo "rsync: pushing (U) local (lz) to webserver (lzserver). (art.luevano.xyz)"
rsync -rtuvPL --delete-after $HOME/luevano.xyz/art/dst/ luevanor:/var/www/art/
